title: The Journey of Videoneers
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.7849463
  brandStrength: 1
  rhythmicContrast: 0.311828
  brandColors:
    - '#83181a'
    - '#030303'
    - '#800000'
    - '#550000'
    - '#780f0f'
  lightness: 0.6899642
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
name: J-Stage Productions
favicon: null
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.1039427
layout_spectrum: 0.6469534
